config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :microposts, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  # 参考元编程proc lambda
  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # 如果删除改模型，依赖的也被删除
  has_many :microposts, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_ADDRESS = /([\w+.]+)@[a-z0-9\-.]+\.[a-z]+/
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_ADDRESS },
                    uniqueness: true
  # has_secure_password方法要求对应模型中有名为password_digest的属性
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # 返回一个随机令牌
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def feed
    Micropost.where("user_id = ?", id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
    # 渲染hello world文本
    render text: "hello world!"
  end

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "请登录"
      redirect_to login_path
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "新建微博成功！"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "删除成功！"
    redirect_to request.referrer || root_url
  end

  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
      # redirect_to user_path(user)
    else
      # flash.now会在下次请求时消失
      flash.now[:danger] = '用户名或密码错误'
      render 'new'
    end
  end

  def destroy
    log_out
    # 在这里url和path我没有发现区别
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_param)
    if @user.save
      log_in @user
      flash[:success] = "欢迎来到百助社区!"
      # 这里 @user 等同于 user_url(@user)
      redirect_back_or @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_param)
      flash[:success] = "修改成功！"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).delete
    flash[:success] = "删除成功"
    redirect_to users_url
  end

  private
    def user_param
      params.require(:user).permit(:name, :email,
                                   :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "花椒网安"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    # 这里的session和session controller不一样，是Rails内置的方法
    session[:user_id] = user.id
  end

  def current_user
    # 如果当前用户为空，则@current_user = User.find_by(id: session[:user])
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  # 友好转向
  def redirect_back_or(default)
    redirect_to session[:forward_url] || default
    session.delete(:forward_url)
  end

  def store_location
    session[:forward_url] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    本网站源码<a href="#">点此查看</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于本站", about_path %></li>
      <li><%= link_to "联系我", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "tutorial", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "首页",  root_path %></li>
        <li><%= link_to "帮助",  help_path %></li>
        <% if logged_in? %>
        <li><%= link_to "网站用户", users_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            账户
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "用户资料", current_user %></li>
            <li><%= link_to "设置", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "退出登录", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "登录", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script> <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>
      <%= full_title(yield(:title)) %>
    </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <%= render 'layouts/shim' %>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
<span class="user"><%= link_to micropost.user.name, micropost.user %></span>
<span class="content"><%= micropost.content %></span>
<span class="timestamp">
  在
  <%= time_ago_in_words(micropost.created_at) %>
  前发布。
  <% if current_user?(micropost.user) %>
    <%= link_to '删除', micropost, method: :delete,
                                  data: { confirm: "确认删除么？" } %>
  <% end %>
</span>
</li>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains
    <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
  <%= render @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_message', object: f.object %>
<div class="field">
  <%= f.text_area :content, placeholder: "编写我的新微博" %>
</div>
<%= f.submit "提交", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "查看我的个人信息", current_user %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "关于") %>
<h1>About</h1>
<p>
  本站由lokyoung编写，为学习Ruby on Rails而做，在此感谢Ruby on Rails Tutorial作者
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "联系我") %>
<h1>联系我</h1>
<p>你可以通过如下联系方式联系我：</p>
<p>Email: lokyoung@outlook.com</p>
<p>Tel: (+86)15727671058</p>

app/views/static_pages/help.html.erb
<% provide(:title, "帮助") %>
<h1>Help</h1>
<p>
  本程序参考ruby on rails tutorial，为学习ruby on rails所做
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>内容测试</h3>
    <%= render 'shared/feed' %>
  </div>
</div>
<% else %>
<div class="center jumbotron">
  <h1>欢迎来到花椒网安</h1>
  <h2>
    这里是花椒网安实验室
  </h2>
  <%= link_to '现在注册！', signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
   | <%= link_to '删除', user, method: :delete,
                              data: { confirm: "你确定要删除么？" }%>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, '修改资料') %>

<h1>修改用户资料</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user)  do |f| %>
      <%= render "shared/error_message", object: f.object %>
      <%= f.label :name, '用户名' %>
      <%= f.text_field :name, class: 'form_control' %>
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form_control' %>
      <%= f.label :password, '密码' %>
      <%= f.text_field :password, class: 'form_control' %>
      <%= f.label :password_confirmation, "确认密码" %>
      <%= f.text_field :password_confirmation, class: 'form_control' %>

      <%= f.submit "保存更改", class: "btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "所有用户") %>
<h1>网站用户</h1>
<%= will_paginate %>
<ul>
  <% @users.each do |user| %>
  <%= render user %>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '注册') %>
<h1>注册</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_message',object: f.object %>
    <%= f.label :name, '用户名' %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
    <%= f.label :password, '密码' %>
    <%= f.password_field :password, class: "form-control" %>
    <%= f.label :password_confirmation, "确认密码" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    <%= f.submit "创建账户", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
        <%= @user.email %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
    <h1>发布信息(<%= @user.microposts.count %>)</h1>
    <ol class="micropost">
      <%= render @microposts %>
    </ol>
    <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>